/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CreatePostRouteImport } from './routes/create-post'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as ChatPostIdDriverIdRouteImport } from './routes/chat.$postId.$driverId'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePostRoute = CreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatPostIdDriverIdRoute = ChatPostIdDriverIdRouteImport.update({
  id: '/chat/$postId/$driverId',
  path: '/chat/$postId/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-post': typeof CreatePostRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/post/$id': typeof PostIdRoute
  '/chat/$postId/$driverId': typeof ChatPostIdDriverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-post': typeof CreatePostRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/post/$id': typeof PostIdRoute
  '/chat/$postId/$driverId': typeof ChatPostIdDriverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/create-post': typeof CreatePostRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/post/$id': typeof PostIdRoute
  '/chat/$postId/$driverId': typeof ChatPostIdDriverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/create-post'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/support'
    | '/post/$id'
    | '/chat/$postId/$driverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/create-post'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/support'
    | '/post/$id'
    | '/chat/$postId/$driverId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/create-post'
    | '/notifications'
    | '/profile'
    | '/signup'
    | '/support'
    | '/post/$id'
    | '/chat/$postId/$driverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CreatePostRoute: typeof CreatePostRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  PostIdRoute: typeof PostIdRoute
  ChatPostIdDriverIdRoute: typeof ChatPostIdDriverIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-post': {
      id: '/create-post'
      path: '/create-post'
      fullPath: '/create-post'
      preLoaderRoute: typeof CreatePostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$postId/$driverId': {
      id: '/chat/$postId/$driverId'
      path: '/chat/$postId/$driverId'
      fullPath: '/chat/$postId/$driverId'
      preLoaderRoute: typeof ChatPostIdDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CreatePostRoute: CreatePostRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  PostIdRoute: PostIdRoute,
  ChatPostIdDriverIdRoute: ChatPostIdDriverIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
